/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_crashinvaders_basisu_BasisuWrapper */

#ifndef _Included_com_crashinvaders_basisu_BasisuWrapper
#define _Included_com_crashinvaders_basisu_BasisuWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_crashinvaders_basisu_BasisuWrapper
 * Method:    getTotalImagesNative
 * Signature: (Ljava/nio/Buffer;I)I
 */
JNIEXPORT jint JNICALL Java_com_crashinvaders_basisu_BasisuWrapper_getTotalImagesNative
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_crashinvaders_basisu_BasisuWrapper
 * Method:    getTotalMipmapLevelsNative
 * Signature: (Ljava/nio/Buffer;II)I
 */
JNIEXPORT jint JNICALL Java_com_crashinvaders_basisu_BasisuWrapper_getTotalMipmapLevelsNative
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     com_crashinvaders_basisu_BasisuWrapper
 * Method:    getImageWidthNative
 * Signature: (Ljava/nio/Buffer;III)I
 */
JNIEXPORT jint JNICALL Java_com_crashinvaders_basisu_BasisuWrapper_getImageWidthNative
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     com_crashinvaders_basisu_BasisuWrapper
 * Method:    getImageHeightNative
 * Signature: (Ljava/nio/Buffer;III)I
 */
JNIEXPORT jint JNICALL Java_com_crashinvaders_basisu_BasisuWrapper_getImageHeightNative
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     com_crashinvaders_basisu_BasisuWrapper
 * Method:    validateHeaderNative
 * Signature: (Ljava/nio/Buffer;I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_crashinvaders_basisu_BasisuWrapper_validateHeaderNative
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     com_crashinvaders_basisu_BasisuWrapper
 * Method:    validateChecksumNative
 * Signature: (Ljava/nio/Buffer;IZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_crashinvaders_basisu_BasisuWrapper_validateChecksumNative
  (JNIEnv *, jclass, jobject, jint, jboolean);

/*
 * Class:     com_crashinvaders_basisu_BasisuWrapper
 * Method:    transcodeRgba32Native
 * Signature: (Ljava/nio/Buffer;III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_crashinvaders_basisu_BasisuWrapper_transcodeRgba32Native
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     com_crashinvaders_basisu_BasisuWrapper
 * Method:    encodeNative
 * Signature: (Ljava/nio/Buffer;IIZZIZZZFIII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_crashinvaders_basisu_BasisuWrapper_encodeNative
  (JNIEnv *, jclass, jobject, jint, jint, jboolean, jboolean, jint, jboolean, jboolean, jboolean, jfloat, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
